name: main
on:
  pull_request:
    branches:
      - main
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install yamllint
        run: sudo apt-get install -y yamllint
      - name: Lint application.yml
        run: yamllint src/main/resources/application.yaml
